### ISSUE TITLE
Approach does not work in jHipster microservices configuration

### ISSUE THREAD

**Issue by jvence** [Falydoor/cognito-jhipster#1]
Trying to set it up in a microservices environment. Gateway works great, as I can log in using Cognito, but when I try access one of the microservices, I get the following error:

java.lang.NullPointerException: null
at com.test.security.oauth2.AudienceValidator.validate(AudienceValidator.java:26)
at com.teest.security.oauth2.AudienceValidator.validate(AudienceValidator.java:13)

Debugging shows that audience variable is null:
`    public OAuth2TokenValidatorResult validate(Jwt jwt) {
        List<String> audience = jwt.getAudience();
        if (audience.stream().anyMatch(allowedAudience::contains)) {
            return OAuth2TokenValidatorResult.success();
        } else {
            log.warn("Invalid audience: {}", audience);
            return OAuth2TokenValidatorResult.failure(error);
        }
    }`

I did configure and modify the files on the microservice as described in your article. Any ideas? Thanks

**Comment by Falydoor** [comment]
Hey Jean,

I'm gonna take a look because there are differences with a classic monolithic app.

**Comment by jvence** [comment]
Great. Let me know if I can be of any assistance in helping you resolve this.

**Comment by Falydoor** [comment]
The issue is because Cognito doesn't include the audience in the access token: https://stackoverflow.com/questions/53148711/why-doesnt-amazon-cognito-return-an-audience-field-in-its-access-tokens

A workaround is to use `client_id` instead, here is the updated `validate` method in `AudienceValidator.java` (must be done in every microservices):

```java
public OAuth2TokenValidatorResult validate(Jwt jwt) {
    String audience = jwt.getClaimAsString("client_id");
    if (allowedAudience.contains(audience)) {
        return OAuth2TokenValidatorResult.success();
    } else {
        log.warn("Invalid audience: {}", audience);
        return OAuth2TokenValidatorResult.failure(error);
    }
}
```

Don't forget to add the `client_id` in the `audience` property of `application.yml`:

```yml
jhipster:
  [...]
  security:
    oauth2:
      audience:
        - account
        - CLIENT_ID
```

**Comment by jvence** [comment]
Not sure how to configure application.yml. Here's what I have but it's not working:
 
```
 security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/[secret]
        registration:
          oidc:
            client-id: [secret]
            client-secret: [secret]

```

**Comment by Falydoor** [comment]
The full path to the property is `jhipster.security.oauth2.audience`, it's at the end of `application.yml`. I know it's confusing with `spring.security.oauth2.client`.

**Comment by jvence** [comment]
Not sure what it looks like. I tried:

```
 security:
    oauth2:
      audience:
        client-id: account
      client:
        provider:
```
allowedAudience (in AudienceValidator) contains [account, api://default], yet jwt.getClaimAsString("client_id") is returning a client id.
